export const INPUT_CHANGE = 'NAV/INPUT_CHANGE'

export const SEARCH_STARTED = 'NAV/SEARCH_STARTED'

export const SEARCH_SUCCESS = 'NAV/SEARCH_SUCCESS'

export const SEARCH_FAILURE = 'NAV/SEARCH_FAILURE'

export const CHANGE_PAGE = 'PAGE/CHANGE_PAGE'