export const CHANGE_AUDIO_STATUS = 'BAR/CHANGE_AUDIO_STATUS'

export const APPEND_THE_SONG = 'PAGE/APPEND_THE_SONG'

export const DELETE_THE_SONG = 'AUDIO/DELETE_THE_SONG'

export const PLAY_THE_SONG_IN_PAGE = 'PAGE/PLAY_THE_SONG'

export const PLAY_THE_SONG_IN_LIST = 'LIST/PLAY_THE_SONG'

export const PLAY_NEXT_SONG = 'AUDIO/PLAY_NEXT_SONG'

// export const GET_SONG = 'AUDIO/GET_AUDIO'

export const GET_LYRIC = 'AUDIO/GET_LYRIC'

export const GET_CURRENT_INDEX = 'AUDIO/GET_CURRENT_INDEX'

export const CHANGE_PLAY_MODE = 'AUDIO/CHANGE_PLAY_MODE'

export  const TOGGLE_SONG_LIST_WINDOW = 'AUDIO/TOGGLE_SONG_LIST_WINDOW'