export const CHANGE_AUDIO_STATUS = 'BAR/CHANGE_AUDIO_STATUS'

export const APPEND_THE_SONG = 'PAGE/APPEND_THE_SONG'

export const DELETE_THE_SONG = 'AUDIO/DELETE_THE_SONG'

export const PLAY_THE_SONG_IN_PAGE = 'PAGE/PLAY_THE_SONG'

export const PLAY_THE_SONG_IN_LIST = 'LIST/PLAY_THE_SONG'

export const PLAY_NEXT_SONG = 'AUDIO/PLAY_NEXT_SONG'

export const GET_LYRIC = 'AUDIO/GET_LYRIC'

export const GET_CURRENT_TIME = 'AUDIO/GET_CURRENT_TIME'

export const CHANGE_PLAY_MODE = 'AUDIO/CHANGE_PLAY_MODE'