export const PLAYLIST_TAG_CHANGE = "PAGE/PLAYLIST_TAG_CHANGE"

export const LOAD_ITEM_DETAIL_STARTED = "PAGE/LOAD_ITEM_DETAIL_STARTED"

export const LOAD_ITEM_DETAIL_SUCCESS = "PAGE/LOAD_ITEM_DETAIL_SUCCESS"

export const DELETE_ITEM_DETAIL = 'PAGE/DELETE_ITEM_DETAIL'

export const PLAYLIST_LOAD_STARTED = 'PAGE/PLAYLIST_LOAD_STARTED'

export const PLAYLIST_LOAD_SUCCESS = 'PAGE/LIST_LOAD_SUCCESS'

export const PLAYLIST_LOAD_FAILURE = 'PAGE/PLAYLIST_LOAD_FAILURE'